### ISSUE TITLE
function eco will fail when there is only a single binary covariate

### ISSUE THREAD

**Issue by zwhou99** [chjackson/ecoreg#2]
For example, if I run the following code:

"""
ng <- 50
N <- rep(100, ng)
set.seed(1)
ctx <- cbind(deprivation = rnorm(ng), mean.income = rnorm(ng))
phi <- cbind(nonwhite = runif(ng), smoke = runif(ng))
sim.df <- as.data.frame(cbind(ctx, phi))
mu <- qlogis(0.05)  ## Disease with approximate 5% prevalence

alpha.c <- log(c(1.01, 1.02))
alpha <- log(c(1.5, 2))

sim1 <- sim.eco(N, ctx=~deprivation+mean.income, binary=~nonwhite,
                    data = sim.df,  mu=mu, alpha.c=alpha.c, alpha=alpha)
aggdata <- as.data.frame(cbind(y=sim1$y, sim.df))
agg.eco <- eco(cbind(y, N) ~ deprivation + mean.income,
               binary = ~ nonwhite,  data = aggdata)
"""

then it will end with an error:
Error in adata[, mod$phi.labs, drop = FALSE] * plogis(q) : non-conformable arrays

**Comment by chjackson** [comment]
Fixed in https://github.com/chjackson/ecoreg/commit/e8b407c2b473c5feea60fb85599987b8eb773fbe
