### ISSUE TITLE
Loglik.eco bug

### ISSUE THREAD

**Issue by sophi890** [chjackson/ecoreg#3]
I think line 298 (within the function loglik.eco) should be 

beta <- if (mod$nnorm > 0) pars[(2+mod$nctx+mod$nbin**effs**):(1+mod$nctx+mod$nbin**effs**+mod$nnorm)] else NULL # individual-level normal covariate effects

instead of 

 beta <- if (mod$nnorm > 0) pars[(2+mod$nctx+mod$nbin):(1+mod$nctx+mod$nbin+mod$nnorm)] else NULL # individual-level normal covariate effects.

(Otherwise the normal argument is faulty and results in a "Hessian is singular" warning)

**Comment by chjackson** [comment]
Fixed in https://github.com/chjackson/ecoreg/commit/ef0589710e96b3f5fc3473bf13a428161a8a996d
