### ISSUE TITLE
Lines 331-347: possible bug when including normal covariates

### ISSUE THREAD

**Issue by sophi890** [chjackson/ecoreg#4]
Should lines 331-347 be replaced with the following? Thank you.
if (mod$nbin + mod$ncat > 0) {
    q <- outer(q, sapply(mod$whicha, function(x) sum(alpha[x])), "+")
  }
  if (mod$nstrata > 1) {
    q <- array(outer(q, qlogis(mod$pstrata), "+"), dim=c(nrow(as.matrix(q)), ncol(as.matrix(q)) * mod$nstrata))
  }
  if (mod$nnorm > 0) {
    if (mod$outcome=="binomial") {
      c <- 16 * sqrt(3) / (15 * pi)
      q <- as.numeric(q + as.vector((adata[,mod$norm.labs,drop=FALSE] %*% beta)) /
                             sqrt (1 + c*c* sapply(attr(adata, "norm.var"), function(x) beta %*% x %*% beta) ) )
    }
    else 
      q <- as.numeric(q + as.vector(adata[,mod$norm.labs,drop=FALSE] %*% beta) +
                            0.5 * sapply(attr(adata, "norm.var"), function(x) beta %*% x %*% beta) )
  }

**Comment by chjackson** [comment]
Fixed in https://github.com/chjackson/ecoreg/commit/feb585afcf4a8099853db65b9c2e912ab5af6da7
